# Generated by Django 5.1.5 on 2025-02-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
