# Generated by Django 5.1.5 on 2025-02-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='balance',
        ),
    ]
