# Generated by Django 5.1.5 on 2025-02-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_investments_packages_withdrawal_delete_contactus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packages',
            options={'ordering': ['id']},
        ),
    ]
