# Generated by Django 5.1.5 on 2025-02-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_withdrawal_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
