# Generated by Django 5.1.5 on 2025-02-17 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_investments_withdrawn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investments',
            name='withdrawn',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='plan',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
