# Generated by Django 5.1.5 on 2025-02-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_packages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investments',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-date']},
        ),
    ]
