# Generated by Django 5.1.5 on 2025-02-14 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_investments_options_alter_withdrawal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='goto_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
