# Generated by Django 5.1.5 on 2025-02-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
