# Generated by Django 5.1.5 on 2025-02-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_investments_options_investments_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
