# Generated by Django 5.1.5 on 2025-02-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_investments_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
