# Generated by Django 5.1.5 on 2025-02-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_payments_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['id']},
        ),
    ]
