# Generated by Django 5.1.5 on 2025-02-15 08:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_investments_status_remove_withdrawal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bonus',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
