# Generated by Django 5.1.5 on 2025-02-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_transaction_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(max_length=100),
        ),
    ]
